<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tyuiu.GojtievTK.Sprint0.Task3.V0.Lib\Tyuiu.GojtievTK.Sprint0.Task3.V0.Lib.csproj" />
  </ItemGroup>

</Project>
